import { createServiceClient } from '@/lib/supabase/server';
import type { NewNewsItem, Feed } from '@/lib/supabase/types';
import { dedupeByCanonicalUrl, normalizeActorId, normalizeContentUrl } from '@/lib/workflow/url';
import { countWords, logIngestEvent } from '@/lib/workflow/events';
import { dueFeeds } from '@/lib/workflow/feed-schedule';

interface ApifyYouTubeVideo {
  title?: string;
  url?: string;
  id?: string;
  thumbnailUrl?: string;
  description?: string;
  date?: string;
  viewCount?: number;
  channelName?: string;
  channelUrl?: string;
  subtitles?: Array<{ plaintext?: string; text?: string; srt?: string; vtt?: string }>;
  transcript?: Array<{ text?: string } | string>;
  transcript_text?: string;
}

const DEFAULT_YOUTUBE_ACTOR = 'streamers~youtube-scraper';

function textFromVideo(video: ApifyYouTubeVideo): string | null {
  const subtitles = video.subtitles
    ?.map((subtitle) => subtitle.plaintext ?? subtitle.text ?? subtitle.srt ?? subtitle.vtt ?? '')
    .filter(Boolean)
    .join(' ');
  if (subtitles?.trim()) return subtitles.trim().slice(0, 12000);

  const transcript = video.transcript
    ?.map((segment) => (typeof segment === 'string' ? segment : segment.text ?? ''))
    .filter(Boolean)
    .join(' ');
  if (transcript?.trim()) return transcript.trim().slice(0, 12000);

  return video.transcript_text?.trim().slice(0, 12000) ?? null;
}

function inputForYouTubeActor(actor: string, channelUrl: string, maxResults: number) {
  if (actor === 'streamers~youtube-scraper') {
    return {
      startUrls: [{ url: channelUrl }],
      maxResults,
      maxResultsShorts: 0,
      maxResultStreams: 0,
      downloadSubtitles: true,
      saveSubsToKVS: true,
      subtitlesLanguage: 'en',
      preferAutoGeneratedSubtitles: true,
      subtitlesFormat: 'plaintext',
      sortVideosBy: 'NEWEST',
      oldestPostDate: '90 days',
    };
  }

  return {
    startUrls: [{ url: channelUrl }],
    maxResults,
    sortBy: 'date',
  };
}

export async function fetchYouTube(workflowRunId?: string): Promise<number> {
  "use step";

  console.log('[fetch-youtube] Starting YouTube fetch via Apify');
  const apiToken = process.env.APIFY_API_TOKEN;
  if (!apiToken) {
    console.warn('[fetch-youtube] APIFY_API_TOKEN not set, skipping');
    await logIngestEvent({
      workflowRunId,
      step: 'fetch:youtube',
      level: 'warning',
      message: 'YouTube scan skipped because APIFY_API_TOKEN is not configured.',
      sourceType: 'youtube',
    });
    return 0;
  }

  const supabase = createServiceClient();

  const { data: feeds, error: feedError } = await supabase
    .from('aitea_feeds')
    .select('*')
    .eq('type', 'youtube')
    .eq('active', true);

  if (feedError || !feeds) {
    throw new Error(`Failed to fetch YouTube feeds: ${feedError?.message}`);
  }

  await logIngestEvent({
    workflowRunId,
    step: 'fetch:youtube',
    message: `Scanning ${feeds.length} YouTube feeds via Apify.`,
    sourceType: 'youtube',
    metrics: { feeds: feeds.length },
  });

  const feedsToScan = dueFeeds(feeds as Feed[]);
  const skipped = feeds.length - feedsToScan.length;

  let totalInserted = 0;

  for (const feed of feedsToScan) {
    const channelUrl = feed.url;
    if (!channelUrl) continue;

    try {
      const config = feed.config as Record<string, unknown>;
      const actor = normalizeActorId(
        config.actor ?? process.env.APIFY_YOUTUBE_ACTOR,
        DEFAULT_YOUTUBE_ACTOR
      );
      const maxResults = Number(config.maxResults ?? 10);

      await logIngestEvent({
        workflowRunId,
        step: 'fetch:youtube:actor',
        message: `Running ${actor} for ${feed.name}.`,
        sourceType: 'youtube',
        sourceName: feed.name,
        metrics: { actor, maxResults, channelUrl },
      });

      const runRes = await fetch(
        `https://api.apify.com/v2/acts/${actor}/run-sync-get-dataset-items?token=${apiToken}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(inputForYouTubeActor(actor, channelUrl, maxResults || 10)),
        }
      );

      if (!runRes.ok) {
        console.error(`[fetch-youtube] Apify error for ${feed.name}: ${runRes.status}`);
        await logIngestEvent({
          workflowRunId,
          step: 'fetch:youtube:error',
          level: 'error',
          message: `${feed.name}: Apify returned HTTP ${runRes.status}.`,
          sourceType: 'youtube',
          sourceName: feed.name,
          metrics: { actor, status: runRes.status },
        });
        continue;
      }

      const videos: ApifyYouTubeVideo[] = await runRes.json();

      const items: NewNewsItem[] = dedupeByCanonicalUrl(videos
        .filter((v) => v.url || v.id)
        .map((video) => {
          const sourceUrl = video.url ?? `https://www.youtube.com/watch?v=${video.id}`;
          const canonicalUrl = normalizeContentUrl(sourceUrl) ?? sourceUrl;
          const transcript = textFromVideo(video);

          return {
            title: video.title ?? 'Untitled Video',
            source_type: 'youtube' as const,
            source_name: video.channelName || feed.name,
            url: canonicalUrl,
            image_url: video.thumbnailUrl ?? null,
            summary: video.description?.slice(0, 300) ?? transcript?.slice(0, 300) ?? null,
            raw_metadata: {
              video_id: video.id,
              published_at: video.date,
              view_count: video.viewCount,
              channel_url: video.channelUrl,
              source_url: sourceUrl,
              canonical_url: canonicalUrl,
              feed_id: feed.id,
              apify_actor: actor,
              transcript_excerpt: transcript?.slice(0, 1200) ?? null,
              idea_source: true,
            },
          };
        }));

      if (items.length > 0) {
        const { data: inserted, error } = await supabase
          .from('aitea_news_items')
          .upsert(items, { onConflict: 'url', ignoreDuplicates: true })
          .select('id');

        if (!error && inserted) {
          totalInserted += inserted.length;
          await logIngestEvent({
            workflowRunId,
            step: 'fetch:youtube:feed',
            level: 'success',
            message: `${feed.name}: ${inserted.length} new videos from ${items.length} candidates.`,
            sourceType: 'youtube',
            sourceName: feed.name,
            metrics: {
              actor,
              returned: videos.length,
              candidates: items.length,
              inserted: inserted.length,
              words: items.reduce((sum, item) => sum + countWords(item.title, item.summary), 0),
            },
          });
        }
      }

      await supabase
        .from('aitea_feeds')
        .update({ last_fetched_at: new Date().toISOString() })
        .eq('id', feed.id);
    } catch (err) {
      console.error(`[fetch-youtube] Failed for ${feed.name}:`, err);
      await logIngestEvent({
        workflowRunId,
        step: 'fetch:youtube:error',
        level: 'error',
        message: `${feed.name} failed during YouTube fetch.`,
        sourceType: 'youtube',
        sourceName: feed.name,
        metrics: { error: String(err) },
      });
    }
  }

  console.log(`[fetch-youtube] Done — inserted ${totalInserted} items`);
  await logIngestEvent({
    workflowRunId,
    step: 'fetch:youtube',
    level: 'success',
    message: `YouTube scan complete: ${totalInserted} new videos.`,
    sourceType: 'youtube',
    metrics: { inserted: totalInserted, skippedByCadence: skipped },
  });
  return totalInserted;
}
